// Y is actually how much up off of the ground excluding object height
// As it stands screen 0 is level 1 but this should be changed later
var screenLayouts = {
	// Intro Page
	0: {
		"background1": {
			"type": "background",
			"x": 0,
			"y": 0,
			"width": 1024,
			"height": 576,
			"texture": "intro",
			"target": "changeScreen(1)",
		},
		"continue": {
			"type": "text",
			"x": 800,
			"y": 538,
			"text": "click to continue",
			"font": "30px Arial",
			"align": "center",
			"stroke": 5,
			"color": "#fff",
		},
	},
	// Tutorial Page
	1: {
		"gamebackground": {
			"type": "background",
			"x": 0,
			"y": 0,
			"width": 768,
			"height": 576,
			"texture": "gameBackground",
		},
		"itembackground": {
			"type": "background",
			"x": 768,
			"y": 0,
			"width": 256,
			"height": 576,
			"texture": "itemBackground",
		},
		"continue": {
			"type": "text",
			"x": 10,
			"y": 538,
			"text": "click to continue",
			"font": "30px Arial",
			"align": "center",
			"stroke": 5,
			"color": "#fff",
			"conditional": "tutorialPhase >=1 && tutorialPhase <= 13 || tutorialPhase === 15"
		},
		"prisoner": {
			"type": "prisoner",
			"x": 10,
			"y": 476,
			"dx": 2.5,
			"dy": 0,
			"width": 36,
			"height": 100,
			"texture": "prisoner1",
			"conditional": "tutorialPhase <= 14",
		},
		"enemy": {
			"type": "object",
			"subtype": "guard",
			"x": 700,
			"y": 476,
			"width": 36,
			"height": 100,
			"texture": "guardFlipped",
			"draggable": false
		},
		"playbutton": {
			"type": "background",
			"x": 784,
			"y": 456,
			"width": 104,
			"height": 104,
			"texture": "playButton",
			"target": "startPrisoner()",
		},
		"resetbutton": {
			"type": "background",
			"x": 904,
			"y": 456,
			"width": 104,
			"height": 104,
			"texture": "resetButton",
			"target": "resetPrisoner()",
		},
		"wall1": {
			"type": "object",
			"subtype": "wall",
			"x": 468,
			"y": 370,
			"dx": 0,
			"dy": 0,
			"width": 300,
			"height": 50,
			"tiling": true,
			"texture": "wall",
			"draggable": false,
		},
		"exit": {
			"type": "object",
			"subtype": "tutorialexit",
			"x": 732,
			"y": 270,
			"dx": 0,
			"dy": 0,
			"width": 36,
			"height": 100,
			"texture": "exit",
			"secondTexture": "exit-closed",
			"draggable": false,
		},
		"shading": {
			"type": "over",
			"x": 0,
			"y": 0,
			"width": 1024,
			"height": 576,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase >= 0 && tutorialPhase <= 5 || tutorialPhase === 15",
		},
		"shadingitems1": {
			"type": "over",
			"x": 0,
			"y": 0,
			"width": 768,
			"height": 576,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase >= 6 && tutorialPhase <= 9",
		},
		"shadingitems2": {
			"type": "over",
			"x": 768,
			"y": 448,
			"width": 256,
			"height": 128,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase >= 6 && tutorialPhase <= 9",
		},
		"shadingbuttons1": {
			"type": "over",
			"x": 0,
			"y": 0,
			"width": 768,
			"height": 576,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase === 10",
		},
		"shadingbuttons2": {
			"type": "over",
			"x": 768,
			"y": 0,
			"width": 256,
			"height": 448,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase === 10",
		},
		"shadingguard1": {
			"type": "over",
			"x": 0,
			"y": 0,
			"width": 690,
			"height": 576,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase === 11",
		},
		"shadingguard2": {
			"type": "over",
			"x": 690,
			"y": 0,
			"width": 60,
			"height": 466,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase === 11",
		},
		"shadingguard3": {
			"type": "over",
			"x": 750,
			"y": 0,
			"width": 274,
			"height": 576,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase === 11",
		},
		"shadingarea1": {
			"type": "over",
			"x": 0,
			"y": 0,
			"width": 300,
			"height": 576,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase === 12",
		},
		"shadingarea2": {
			"type": "over",
			"x": 375,
			"y": 0,
			"width": 649,
			"height": 576,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase === 12",
		},
		"shadingarea3": {
			"type": "over",
			"x": 300,
			"y": 0,
			"width": 75,
			"height": 526,
			"alpha": 0.5,
			"texture": "black",
			"conditional": "tutorialPhase === 12",
		},
		"jerry": {
			"type": "over",
			"x": 864,
			"y": 416,
			"width": 140,
			"height": 140,
			"flipped": true,
			"delay": 1000,
			"texture": "jerry",
			"conditional": "tutorialPhase === 0",
		},
		"jerrybubble1": {
			"type": "over",
			"x": 130,
			"y": 416,
			"width": 336,
			"height": 140,
			"texture": "textbubbleS",
			"target": "progressTutorial()",
			"conditional": "tutorialPhase === 0",
		},
		"jerryyes": {
			"type": "text",
			"x": 146,
			"y": 470,
			"text": "Ugh, let's get this over with.",
			"wordWrap": 300,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"target": "startTutorial()",
			"conditional": "tutorialPhase === 0",
		},
		"or": {
			"type": "text",
			"x": 463,
			"y": 465,
			"text": "or",
			"font": "30px Arial",
			"align": "center",
			"stroke": 5,
			"color": "#fff",
			"conditional": "tutorialPhase === 0",
		},
		"jerrybubble2": {
			"type": "over",
			"x": 508,
			"y": 416,
			"width": 336,
			"height": 140,
			"texture": "textbubbleS",
			"target": "changeScreen(2)",
			"conditional": "tutorialPhase === 0",
		},
		"jerryno": {
			"type": "text",
			"x": 540,
			"y": 457,
			"text": "No way man, I'm sick of this.",
			"wordWrap": 300,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 0",
		},
		"supervisor": {
			"type": "over",
			"x": 20,
			"y": 20,
			"width": 140,
			"height": 140,
			"flipped": true,
			"texture": "blaine",
			"conditional": "tutorialPhase === 0 || (tutorialPhase >= 6 && tutorialPhase <= 13) || tutorialPhase === 15",
		},
		"superbubble": {
			"type": "over",
			"x": 160,
			"y": 20,
			"width": 824,
			"height": 140,
			"flipped": true,
			"texture": "textbubbleL",
			"conditional": "tutorialPhase === 0",
		},
		"superwords": {
			"type": "text",
			"x": 195,
			"y": 60,
			"text": "Blaine (Supervisor): Hey there bud, you ready for our weekly training session? (Would you like to play the tutorial?)",
			"wordWrap": 800,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 0",
		},
		"paper": {
			"type": "over",
			"x": 256,
			"y": 8,
			"width": 512,
			"height": 560,
			"texture": "paper",
			"target": "progressTutorial(); sounds['paper'].stop(); sounds['paper'].play();",
			"conditional": "tutorialPhase >= 1 && tutorialPhase <= 5",
		},
		"coverinteractive": {
			"type": "over",
			"x": 0,
			"y": 0,
			"width": 1024,
			"height": 576,
			"texture": "blank",
			"target": "",
			"conditional": "tutorialPhase >= 1 && tutorialPhase <= 5",
		},
		"diarytitle": {
			"type": "text",
			"x": 350,
			"y": 70,
			"text": "Jerry's Diary",
			"font": "24px Arial",
			"align": "left",
			"color": "#000",
			"conditional": "tutorialPhase >= 1 && tutorialPhase <= 5",
		},
		"diarytext": {
			"type": "text",
			"x": 350,
			"y": 125,
			"text": "Day 1: So I got a job today at the local prison and it may not be the most glamorous job, but a paycheck's a paycheck, am'i'rite?",
			"font": "24px Arial",
			"wordWrap": 400,
			"lineHeight": 64,
			"align": "left",
			"color": "#000",
			"conditional": "tutorialPhase === 1",
		},
		"diarytext2": {
			"type": "text",
			"x": 350,
			"y": 125,
			"text": "Day 3: So today I had to clean up after a massive riot, the entire mess hall was ruined and my supervisor, Blaine, just handed me a mop and said 'get to it bud'. God I hate when he calls me bud.",
			"font": "24px Arial",
			"wordWrap": 400,
			"lineHeight": 64,
			"align": "left",
			"color": "#000",
			"conditional": "tutorialPhase === 2",
		},
		"diarytext3": {
			"type": "text",
			"x": 350,
			"y": 125,
			"text": "Day 13: So I may have been incorrect diary, the things I have to do for a paycheck here are either so extremely boring or so extremely tedious that the paycheck may not be #worth.",
			"font": "24px Arial",
			"wordWrap": 400,
			"lineHeight": 64,
			"align": "left",
			"color": "#000",
			"conditional": "tutorialPhase === 3",
		},
		"diarytext4": {
			"type": "text",
			"x": 350,
			"y": 125,
			"text": "Day 69: THAT'S IT, I CAN'T STAND IT ANYMORE. I'M DONE HERE, I AM CONVINCED I AM STUCK IN AN ETERNAL PURGATORY IN THE FORM OF ORANGE JUMPSUITS AND MEATLOAF MONDAY. WHO EATS MEATLOAF.",
			"font": "24px Arial",
			"wordWrap": 400,
			"lineHeight": 64,
			"align": "left",
			"color": "#000",
			"conditional": "tutorialPhase === 4",
		},
		"diarytext5": {
			"type": "text",
			"x": 350,
			"y": 125,
			"text": "Day 73: So turns out there's a prison policy that employees may only resign at the end of every quarter. The next being in 4 months... Whelp, time to get fired!",
			"font": "24px Arial",
			"wordWrap": 400,
			"lineHeight": 64,
			"align": "left",
			"color": "#000",
			"conditional": "tutorialPhase === 5",
		},
		"tutorialbubble": {
			"type": "over",
			"x": 160,
			"y": 20,
			"width": 520,
			"height": 140,
			"flipped": true,
			"texture": "textbubbleM",
			"conditional": "tutorialPhase >= 6 && tutorialPhase <= 13 || tutorialPhase === 15",
		},
		"tutorialwords": {
			"type": "text",
			"x": 195,
			"y": 45,
			"text": "Blaine: So just a reminder, we have a new shipment of various doo-hickeys over here that the prisoners may use to escape.",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 6",
		},
		"clicktarget": {
			"type": "over",
			"x": 0,
			"y": 0,
			"width": 1024,
			"height": 576,
			"texture": "blank",
			"target": "progressTutorial()",
			"conditional": "tutorialPhase >= 6 && tutorialPhase <= 13 || tutorialPhase === 15",
		},
		"jumpy": {
			"type": "object",
			"subtype": "jumpfield",
			"x": 800,
			"y": 40,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 25,
			"texture": "jumppad",
			"draggable": true,
		},
		"jumpy2": {
			"type": "object",
			"subtype": "jumpfield",
			"x": 870,
			"y": 40,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 25,
			"texture": "jumppad",
			"draggable": true,
		},
		"turn": {
			"type": "object",
			"subtype": "turn",
			"x": 812,
			"y": 85,
			"dx": 0,
			"dy": 0,
			"width": 28,
			"height": 52,
			"texture": "turn",
			"secondTexture": "turnDown",
			"draggable": true,
		},
		"turn2": {
			"type": "object",
			"subtype": "turn",
			"x": 876,
			"y": 85,
			"dx": 0,
			"dy": 0,
			"width": 28,
			"height": 52,
			"texture": "turn",
			"secondTexture": "turnDown",
			"draggable": true,
		},
		"stop": {
			"type": "object",
			"subtype": "stop",
			"x": 792,
			"y": 157,
			"dx": 0,
			"dy": 0,
			"width": 60,
			"height": 60,
			"texture": "stop",
			"secondTexture": "blank",
			"draggable": true,
		},
		"stop2": {
			"type": "object",
			"subtype": "stop",
			"x": 864,
			"y": 157,
			"dx": 0,
			"dy": 0,
			"width": 60,
			"height": 60,
			"texture": "stop",
			"secondTexture": "blank",
			"draggable": true,
		},
		"itemhighlight": {
			"type": "over",
			"x": 768,
			"y": 0,
			"width": 256,
			"height": 448,
			"texture": "highlightRect",
			"conditional": "tutorialPhase >= 6 && tutorialPhase <= 9",
		},
		"itemwords1": {
			"type": "text",
			"x": 195,
			"y": 35,
			"text": "Blaine: The first item here is a jump pad, it can be used to displace the prisoners high into the air because this is something we need on a regular basis.",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 7",
		},
		"jumphighlight": {
			"type": "over",
			"x": 790,
			"y": 30,
			"width": 70,
			"height": 45,
			"texture": "highlight",
			"conditional": "tutorialPhase === 7",
		},
		"itemwords2": {
			"type": "text",
			"x": 195,
			"y": 35,
			"text": "Blaine: And here's a good 'ol fashion stop sign. These prisoners really respect the rules of the road so they will stop dead in their tracks the first time they hit this.",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 9",
		},
		"turnhighlight": {
			"type": "over",
			"x": 790,
			"y": 147,
			"width": 80,
			"height": 80,
			"texture": "highlight",
			"conditional": "tutorialPhase === 9",
		},
		"itemwords3": {
			"type": "text",
			"x": 195,
			"y": 35,
			"text": "Blaine: Next we have the classic wet floor sign. This sign will infuriate the prisoner so much that they turn around after knocking the poor sign over.",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 8",
		},
		"stophighlight": {
			"type": "over",
			"x": 790,
			"y": 75,
			"width": 48,
			"height": 72,
			"texture": "highlight",
			"conditional": "tutorialPhase === 8",
		},
		"spothighlight": {
			"type": "over",
			"x": 300,
			"y": 526,
			"width": 75,
			"height": 50,
			"texture": "highlight",
			"conditional": "tutorialPhase === 12",
		},
		"buttonshighlight": {
			"type": "over",
			"x": 768,
			"y": 448,
			"width": 256,
			"height": 128,
			"texture": "highlight",
			"conditional": "tutorialPhase === 10",
		},
		"buttonwords": {
			"type": "text",
			"x": 195,
			"y": 35,
			"text": "Blaine: And these buttons right here allow us to control when the prisoner starts moving, or even reset them back in time! Crazy how far technology has come.",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 10",
		},
		"guardwords": {
			"type": "text",
			"x": 195,
			"y": 35,
			"text": "Blaine: Oh yeah, and here's one of our own. Just a friendly guard who will bring your prisoner back to his cell. Hi-Five Joe!",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 11",
		},
		"guardhighlight": {
			"type": "over",
			"x": 690,
			"y": 466,
			"width": 60,
			"height": 110,
			"texture": "highlight",
			"conditional": "tutorialPhase === 11",
		},
		"tutorialwords1": {
			"type": "text",
			"x": 195,
			"y": 35,
			"text": "Blaine: So, long story short, if you value your job, you definitely wouldn't want to move a jump pad here because then the prisoner could escape, got it?",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 12",
		},
		"tutorialwords2": {
			"type": "text",
			"x": 195,
			"y": 50,
			"text": "Blaine: How about you give it a go, just remember, DON'T put the jumping pad exactly where I said.",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 13",
		},
		"tutorialwords3": {
			"type": "text",
			"x": 195,
			"y": 45,
			"text": "Blaine: Hm, so you managed to do exactly the one thing I told you to avoid. I'm keeping my eye on you, bud.",
			"wordWrap": 480,
			"font": "24px Arial",
			"align": "center",
			"color": "#000",
			"conditional": "tutorialPhase === 15",
		},
	},
	// Main Menu
	2: {
		"prisoner1": {
			"type": "background",
			"x": 72,
			"y": 48,
			"width": 240,
			"height": 368,
			"texture": "menuprisoner1",
			"target": "changeScreen(3)",
			"conditional": "freedPrisoners[0] === false"
		},
		"prisoner2": {
			"type": "background",
			"x": 382,
			"y": 48,
			"width": 240,
			"height": 368,
			"texture": "menuprisoner2",
			"target": "changeScreen(4)",
			"conditional": "freedPrisoners[1] === false"
		},
		"prisoner3": {
			"type": "background",
			"x": 692,
			"y": 48,
			"width": 240,
			"height": 368,
			"texture": "menuprisoner3",
			"target": "changeScreen(5)",
			"conditional": "freedPrisoners[2] === false"
		},
		"background": {
			"type": "background",
			"x": 0,
			"y": 0,
			"width": 1024,
			"height": 576,
			"texture": "mainmenu",
		},
		"mainmenutext": {
			"type": "text",
			"x": 300,
			"y": 480,
			"text": "Select a prisoner to free.",
			"stroke": 5,
			"font": "40px Arial",
			"align": "center",
			"color": "#fff",
			"conditional": "!(freedPrisoners[0] === true && freedPrisoners[1] === true && freedPrisoners[2] === true)"
		},
		"victorytext": {
			"type": "text",
			"x": 23,
			"y": 480,
			"text": "You freed them all, you've successfully been fired!..?..!",
			"stroke": 5,
			"font": "40px Arial",
			"align": "center",
			"color": "#fff",
			"conditional": "freedPrisoners[0] === true && freedPrisoners[1] === true && freedPrisoners[2] === true"
		},
	},
	// Level 1
	3: {
		"gamebackground": {
			"type": "background",
			"x": 0,
			"y": 0,
			"width": 768,
			"height": 576,
			"texture": "gameBackground"
		},
		"itembackground": {
			"type": "background",
			"x": 768,
			"y": 0,
			"width": 256,
			"height": 576,
			"texture": "itemBackground",
		},
		"playbutton": {
			"type": "background",
			"x": 784,
			"y": 456,
			"width": 104,
			"height": 104,
			"texture": "playButton",
			"target": "startPrisoner()",
		},
		"resetbutton": {
			"type": "background",
			"x": 904,
			"y": 456,
			"width": 104,
			"height": 104,
			"texture": "resetButton",
			"target": "resetPrisoner()",
		},
		"prisoner": {
			"type": "prisoner",
			"x": 10,
			"y": 476,
			"dx": 2.5,
			"dy": 0,
			"width": 36,
			"height": 100,
			"texture": "prisoner1",
			"secondTexture": "prisoner1Flipped",
		},
		"jumpy": {
			"type": "object",
			"subtype": "jumpfield",
			"x": 800,
			"y": 40,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 25,
			"texture": "jumppad",
			"draggable": true,
		},
		"jumpy2": {
			"type": "object",
			"subtype": "jumpfield",
			"x": 870,
			"y": 40,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 25,
			"texture": "jumppad",
			"draggable": true,
		},
		"turn": {
			"type": "object",
			"subtype": "turn",
			"x": 812,
			"y": 85,
			"dx": 0,
			"dy": 0,
			"width": 28,
			"height": 52,
			"texture": "turn",
			"secondTexture": "turnDown",
			"draggable": true,
		},
		"turn2": {
			"type": "object",
			"subtype": "turn",
			"x": 876,
			"y": 85,
			"dx": 0,
			"dy": 0,
			"width": 28,
			"height": 52,
			"texture": "turn",
			"secondTexture": "turnDown",
			"draggable": true,
		},
		"stop": {
			"type": "object",
			"subtype": "stop",
			"x": 792,
			"y": 157,
			"dx": 0,
			"dy": 0,
			"width": 60,
			"height": 60,
			"texture": "stop",
			"secondTexture": "blank",
			"draggable": true,
		},
		"stop2": {
			"type": "object",
			"subtype": "stop",
			"x": 864,
			"y": 157,
			"dx": 0,
			"dy": 0,
			"width": 60,
			"height": 60,
			"texture": "stop",
			"secondTexture": "blank",
			"draggable": true,
		},
		"wall1": {
			"type": "object",
			"subtype": "wall",
			"x": 468,
			"y": 350,
			"width": 300,
			"height": 50,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"wall2": {
			"type": "object",
			"subtype": "wall",
			"x": 0,
			"y": 240,
			"width": 300,
			"height": 50,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"enemy": {
			"type": "object",
			"subtype": "guard",
			"x": 600,
			"y": 476,
			"width": 36,
			"height": 100,
			"texture": "guardFlipped",
			"draggable": false
		},
		"victory": {
			"type": "object",
			"subtype": "exit",
			"x": 0,
			"y": 140,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 100,
			"texture": "exit",
			"secondTexture": "exit-closed",
			"flipped": true,
			"draggable": false
		},
	},
	// Level 2
	4: {
		"gamebackground": {
			"type": "background",
			"x": 0,
			"y": 0,
			"width": 768,
			"height": 576,
			"texture": "gameBackground"
		},
		"itembackground": {
			"type": "background",
			"x": 768,
			"y": 0,
			"width": 256,
			"height": 576,
			"texture": "itemBackground",
		},
		"playbutton": {
			"type": "background",
			"x": 784,
			"y": 456,
			"width": 104,
			"height": 104,
			"texture": "playButton",
			"target": "startPrisoner()",
		},
		"resetbutton": {
			"type": "background",
			"x": 904,
			"y": 456,
			"width": 104,
			"height": 104,
			"texture": "resetButton",
			"target": "resetPrisoner()",
		},
		"prisoner": {
			"type": "prisoner",
			"x": 110,
			"y": 476,
			"dx": 2.5,
			"dy": 0,
			"width": 36,
			"height": 100,
			"texture": "prisoner2",
			"secondTexture": "prisoner2Flipped",
		},
		"jumpy": {
			"type": "object",
			"subtype": "jumpfield",
			"x": 800,
			"y": 40,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 25,
			"texture": "jumppad",
			"draggable": true,
		},
		"jumpy2": {
			"type": "object",
			"subtype": "jumpfield",
			"x": 870,
			"y": 40,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 25,
			"texture": "jumppad",
			"draggable": true,
		},
		"turn": {
			"type": "object",
			"subtype": "turn",
			"x": 812,
			"y": 85,
			"dx": 0,
			"dy": 0,
			"width": 28,
			"height": 52,
			"texture": "turn",
			"secondTexture": "turnDown",
			"draggable": true,
		},
		"turn2": {
			"type": "object",
			"subtype": "turn",
			"x": 876,
			"y": 85,
			"dx": 0,
			"dy": 0,
			"width": 28,
			"height": 52,
			"texture": "turn",
			"secondTexture": "turnDown",
			"draggable": true,
		},
		"stop": {
			"type": "object",
			"subtype": "stop",
			"x": 792,
			"y": 157,
			"dx": 0,
			"dy": 0,
			"width": 60,
			"height": 60,
			"texture": "stop",
			"secondTexture": "blank",
			"draggable": true,
		},
		"stop2": {
			"type": "object",
			"subtype": "stop",
			"x": 864,
			"y": 157,
			"dx": 0,
			"dy": 0,
			"width": 60,
			"height": 60,
			"texture": "stop",
			"secondTexture": "blank",
			"draggable": true,
		},
		"wall1": {
			"type": "object",
			"subtype": "wall",
			"x": 100,
			"y": 390,
			"width": 520,
			"height": 50,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"wall2": {
			"type": "object",
			"subtype": "wall",
			"x": 50,
			"y": 390,
			"width": 50,
			"height": 186,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"wall3": {
			"type": "object",
			"subtype": "wall",
			"x": 450,
			"y": 180,
			"width": 200,
			"height": 50,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"victory": {
			"type": "object",
			"subtype": "exit",
			"x": 600,
			"y": 80,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 100,
			"texture": "exit",
			"secondTexture": "exit-closed",
			"draggable": false
		},
	},
	// Level 3
	5: {
		"gamebackground": {
			"type": "background",
			"x": 0,
			"y": 0,
			"width": 768,
			"height": 576,
			"texture": "gameBackground"
		},
		"itembackground": {
			"type": "background",
			"x": 768,
			"y": 0,
			"width": 256,
			"height": 576,
			"texture": "itemBackground",
		},
		"playbutton": {
			"type": "background",
			"x": 784,
			"y": 456,
			"width": 104,
			"height": 104,
			"texture": "playButton",
			"target": "startPrisoner()",
		},
		"resetbutton": {
			"type": "background",
			"x": 904,
			"y": 456,
			"width": 104,
			"height": 104,
			"texture": "resetButton",
			"target": "resetPrisoner()",
		},
		"prisoner": {
			"type": "prisoner",
			"x": 10,
			"y": 476,
			"dx": 2.5,
			"dy": 0,
			"width": 36,
			"height": 100,
			"texture": "prisoner3",
			"secondTexture": "prisoner3Flipped",
		},
		"enemy": {
			"type": "object",
			"subtype": "guard",
			"x": 255,
			"y": 291,
			"width": 36,
			"height": 100,
			"texture": "guardFlipped",
			"draggable": false
		},
		"jumpy": {
			"type": "object",
			"subtype": "jumpfield",
			"x": 800,
			"y": 40,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 25,
			"texture": "jumppad",
			"draggable": true,
		},
		"jumpy2": {
			"type": "object",
			"subtype": "jumpfield",
			"x": 870,
			"y": 40,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 25,
			"texture": "jumppad",
			"draggable": true,
		},
		"turn": {
			"type": "object",
			"subtype": "turn",
			"x": 812,
			"y": 85,
			"dx": 0,
			"dy": 0,
			"width": 28,
			"height": 52,
			"texture": "turn",
			"secondTexture": "turnDown",
			"draggable": true,
		},
		"turn2": {
			"type": "object",
			"subtype": "turn",
			"x": 876,
			"y": 85,
			"dx": 0,
			"dy": 0,
			"width": 28,
			"height": 52,
			"texture": "turn",
			"secondTexture": "turnDown",
			"draggable": true,
		},
		"stop": {
			"type": "object",
			"subtype": "stop",
			"x": 792,
			"y": 157,
			"dx": 0,
			"dy": 0,
			"width": 60,
			"height": 60,
			"texture": "stop",
			"secondTexture": "blank",
			"draggable": true,
		},
		"stop2": {
			"type": "object",
			"subtype": "stop",
			"x": 864,
			"y": 157,
			"dx": 0,
			"dy": 0,
			"width": 60,
			"height": 60,
			"texture": "stop",
			"secondTexture": "blank",
			"draggable": true,
		},
		"wall1": {
			"type": "object",
			"subtype": "wall",
			"x": 135,
			"y": 401,
			"width": 50,
			"height": 175,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"wall2": {
			"type": "object",
			"subtype": "wall",
			"x": 235,
			"y": 416,
			"width": 425,
			"height": 50,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"wall3": {
			"type": "object",
			"subtype": "wall",
			"x": 235,
			"y": 391,
			"width": 50,
			"height": 25,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"wall4": {
			"type": "object",
			"subtype": "wall",
			"x": 610,
			"y": 391,
			"width": 50,
			"height": 25,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"wall5": {
			"type": "object",
			"subtype": "wall",
			"x": 460,
			"y": 341,
			"width": 200,
			"height": 50,
			"tiled": true,
			"texture": "wall",
			"draggable": false
		},
		"victory": {
			"type": "object",
			"subtype": "exit",
			"x": 460,
			"y": 241,
			"dx": 0,
			"dy": 0,
			"width": 50,
			"height": 100,
			"texture": "exit",
			"secondTexture": "exit-closed",
			"draggable": false
		},
	}
}